server:
  port: 8081
  
spring:
  profiles:
    active:
    - test
    
  application:
    name: authentication-service

  security:
    oauth2:
      client:         
        registration:
          github:
            client-id: your_github_client_id
            client-secret: your_github_client_secret
          google:
            client-id: your_google_client_id
            client-secret: your_google_client_secret
               
#        provider:
#          custom-google:
#            issuer-uri: https://accounts.google.com
 
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    